### ISSUE TITLE
Accessibility should not be hidden away under "Miscellaneous"

### ISSUE THREAD

**Issue by lisbethdavies** [freeCodeCamp/guide#319]
Making websites and apps accessible is way too important and its current location gives the continued impression to new developers that it's an afterthought, something you fix with a few alt tags just before launch and only to improve SEO.

Please consider making it a top level topic, just before Agile.

**Comment by Bouncey** [comment]
@lisbethdavies I can assure you this was not intentional. I originally filled the guide with topics from the wiki section of the forum. I did some basic filtering into programming languages because they were easier to filter against.

Anything that didn't fit into one of those categories was lumped into a `to-be-sorted` directory, which  was later renamed to `misc.`. That is one of the reasons that directory has so many topics in it.

I would gladly make all things `a11y` related a top level category. I am open to PR's also :+1: 

Please be gentle with us, this guide is only new and still requires some (*a lot of*) polishing.

**Comment by lisbethdavies** [comment]
I'm so very glad to hear that it's not intentional - thank you! It's a wonderful project, you and the rest of the team have my total respect.

PR's = pull requests? Github novice seeks clarification ;-)

**Comment by Bouncey** [comment]
@lisbethdavies I am actually blushing, thank you :blush: I am only a code slinger here. Many other people have spent a lot of time writing the content for us to read.

Yes a PR is a pull request :+1:

**Comment by mabuyo** [comment]
I took a shot at doing this. To clarify: we want this [article](https://guide.freecodecamp.org/miscellaneous/accessibility-basics) to be a top-level article under a new section called "Accessibility". Took a screenshot of what I did:

<img width="1243" alt="screen shot 2017-10-07 at 1 55 09 pm" src="https://user-images.githubusercontent.com/6900407/31310510-44b3fb4c-ab67-11e7-8609-b05b717abbdc.png">

Should the content be in an another article under Accessibility, or should it be how it's shown in the screenshot?

**Comment by mabuyo** [comment]
Just checked PRs, looks like this was acknowledged in #775!

**Comment by pertrai1** [comment]
I see this section now. That should be enough to close this issue should it not?

**Comment by johnkennedy9147** [comment]
Issue resolved by #775
