### ISSUE TITLE
Navigation structure too flat, also inconsistent between languages. Article naming inconsistent.

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/guide#414]
I think it would greatly benefit users if the tree structure had more layers and if those layers were consistent between sections for each language.

For example in the JavaScript section you get a big list of articles and there are around 10 on loops. With the article naming being inconsistent its hard to find all the loop articles.  If we used a structure like JavaScript / Loops / ... for example they would be grouped in a logical way greatly aiding users in finding all the articles on the topic of interest. A user might for example know they can do looping but not know the commands so find it difficult to identify which articles would be helpful.

If we establish a consistent structure across languages then it will make it easy for people to navigate the resources.

**Comment by Bouncey** [comment]
I would be interested in seeing a PR on this :+1:

**Comment by johnkennedy9147** [comment]
I'd like to take a stab at this!

Am I right in thinking the side Nav is built out from the directory structure

so taking JavaScript loops as an example, if I 
-add new directory to guides/src/pages/javascript/
-move the articles 
-create / update index.md with something useful 

that'll sort it?

**Comment by systimotic** [comment]
@johnkennedy9147 Thanks for taking this on! 

The URL is built from the directory structure. The names in the SideNav come from the front matter:
```markdown
---
title: This is the title in the navigation
---
```
The steps you mentioned should do the trick 👍

**Comment by johnkennedy9147** [comment]
PR #459 submitted to make a start on this - began with a JavaScript loops directory

**Comment by systimotic** [comment]
@johnkennedy9147 Do you have more places where this should happen? I know that @davcri is working on doing this for the Java section. It would be great to create a list of things that need to be done, so we can follow our progress and what we still have left to do.

**Comment by johnkennedy9147** [comment]
@systimotic I think most sections would benefit from a hierarchical structure, though less important on sections with relatively few articles. HTML, CSS, Java, Javascript, Python, Agile and SQL I think are the most urgent due to combination of number of articles and what I think will be most heavily used sections of the Guide.  Just submitted PR #630 as another step on this.

**Comment by ALeilands** [comment]
I agree about the confusing navigation. I think that not only individual language section structure should be more consistent, but also the Guide in general should be more organised. If the main idea is not to have a bunch of information that should be accessed mainly by searching but to have a roadmap of sorts that can be explored through different paths, it should be more structured, with these... paths. Programming languages should be in a separate folder, text editors should have a folder under "tools", and so on. Maybe I have misunderstood the purpose of all this. Also, the articles should really be basic and link to resources with extended content, otherwise some of the content will become outdated soon enough. Sure, some of it is timeless, but still.
