### ISSUE TITLE
No Android App Development guide in src folder?

### ISSUE THREAD

**Issue by geekanamika** [freeCodeCamp/guide#4903]
I wanted to contribute for Hactober fest. I am an android developer but couldn't find any src which corresponds to android development. There is one Mobile app Development folder but it further includes only React development and more. Can you please guide if i am missing something ?

**Comment by Bouncey** [comment]
Feel free to add the relevant categories for your article.

Any parent directories will need stubs, which can be done using `yarn run normalise` and committing the changes

**Comment by MauroCoppola** [comment]
Hi, I'd like to contribute to the Android guide for mobile applications development section. Is it still possible?

**Comment by Asjas** [comment]
Hi @MauroCoppola 

There is currently a Android Development folder that has been merged since October. You can refer to the [current Android Development Page](https://github.com/freeCodeCamp/guide/tree/master/src/pages/android-development).

This issue will be closed since it seems someone else has created it during Hacktoberfest and we merged their PR. Please feel free however to expand upon it with more content and to create sub-folders about different parts of Android Development.

Please refer to our [Contributing Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md) if you have any questions about contributing or feel free to reach out to us in the freeCodeCamp Gitter [Contributors Room](https://gitter.im/FreeCodeCamp/Contributors).
