### ISSUE TITLE
Incorrectly named articles can pass build tests if added where index.md exists.

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/guide#7852]
If someone creates a file with incorrect name in a folder in which an index.md already exists the build tests will still pass. Examples PR #2324 (corrected before merge) PR #445 Merged without being corrected (PR #7851 submitted to fix.)

We need to add further check(s) to catch this.

This doesn't break the build as the articles are simply ignored.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by adiparab14** [comment]
@johnkennedy9147 I think changing the isAFileRE constant in regEx.js to check for index.md should work.

**Comment by johnkennedy9147** [comment]
@adiparab14 Yeah, I think that would work. There are files in the repository correctly called something other than index.md but I don't think the build checks are looking in the directories containing them.
@systimotic what do you think?

**Comment by systimotic** [comment]
Thanks for the input.

@johnkennedy9147 is correct in saying that the root directory (src/pages/) is not read, and that is should be the only directory that has files that are not named `index.md`

Sadly, just changing the regex won't fix the issue here, as it will continue to ignore file that are not named `index.md`

I think the best approach would be to change things up the `readIndex` function around here: https://github.com/systimotic/guides/commit/54816bed35af6dcba1a860472dab587576c8dd0e#diff-6c5a2e4f2eb38f7aa11f701f08de26ffR9
Instead of reading the index.md, we could read the entire directory. If there is any file that is not named index.md, we throw an error. Otherwise, the content of the `index.md` file is returned.

**Comment by Bouncey** [comment]
Addressed in #8356
