### ISSUE TITLE
Certificate section of guide is empty

### ISSUE THREAD

**Issue by joshalling** [freeCodeCamp/guide#8333]
The Certificates section of the guide seems to be empty. I tested this in Chrome, Firefox, and the Android Browser

To reproduce:
- go to https://guide.freecodecamp.org/
- click on Certificates

I'm not sure if I am just missing something as I am not very familiar with the guide.

**Comment by Asjas** [comment]
@joshalling I just tested it and I'm seeing content to the right. Are you not seeing the same?

![screenshot_1](https://user-images.githubusercontent.com/3828967/43600298-85345d60-968a-11e8-9c2f-a60be6cb7a22.png)

**Comment by joshalling** [comment]
@Asjas I'm talking about the menu on the left. When I click on Certificates the caret points downward like its open, but there is nothing to select.

**Comment by Asjas** [comment]
Ah okay, now I see it. 

The folders inside the [certifications](https://github.com/freeCodeCamp/guide/tree/master/src/pages/certifications) folder isn't being seen and compiled. I'm testing to see why this is happening.

**Comment by Asjas** [comment]
Okay I found the problem. 

The sub-folders don't have their own `index.md` files. Which is why they are being ignored. Each and every folder needs a `index.md` file for it to be recognized and to be compiled.

I'm going to mark this as `help wanted`. Anyone is free to pick this up and fix it. You'd have to go into each and every sub-folder in the [certifications](https://github.com/freeCodeCamp/guide/tree/master/src/pages/certifications) folder and create a corresponding `index.md` file for that folder.

**Comment by joshalling** [comment]
I'll work on this. I'm just adding stubs in each subfolder, correct?

**Comment by Asjas** [comment]
@joshalling Yes that is correct. :+1:
