### ISSUE TITLE
Page order in sidebar menu

### ISSUE THREAD

**Issue by joshalling** [freeCodeCamp/guide#8387]
I just rebased my fork and started the development server, and the order of the pages in the side menu is now all random (see pic below). This might be related to #8382, or a different recent change, or it could just be that my dev environment has been corrupted somehow. Has anyone else ran into this issue lately while running the site locally?

![screenshot from 2018-08-17 08-22-06](https://user-images.githubusercontent.com/7757937/44272020-e1f9b580-a1f8-11e8-9e70-49049ea51506.png)

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by JimmayVV** [comment]
this is really weird...

What's interesting is I rebased as well, and I see the same issues you do, and I was the one that submitted the PR #8382 - so either I missed something completely obvious, or something else is causing the children in the side panel to appear out of order.

Whatever is causing it, though, doesn't appear to be live in production, so it seems like it must be something else causing it. I'm curious how this happened though.

**Comment by JimmayVV** [comment]
I have been looking into this deeper, and it seems something that is baked into Gatsby. I don't know much about Gatsby, so I'm afraid of doing more harm than good by digging into this deeper, but while looking at GraphiQL on development, it looks like it is importing the pages out of alphabetical order.

If you replicate the GraphQL query from `layout.js` into `http://localhost:8000/___graphql` you will see the results are equally out of order. Perhaps this is a bug with the Dev environment baked right into Gatsby, or something else... however I did just want to add this context to what we are looking at.

This might be something we just have to live with in the dev environment, since production seems stable, but I defer to those who have more knowledge on this subject than me
