### ISSUE TITLE
Improve Repo page

### ISSUE THREAD

**Issue by hiparthparth** [freeCodeCamp/guide#8621]
I am looking for the place on this repo where I can edit this page- https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords .
Any help would be appreciated

---

> ✅️ By submitting this issue, I have verified the following

- [x ] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by jsjoeio** [comment]
@hiparthparth - Please use the GitHub search to find guide pages next time instead of opening an issue. Here's a quick screen recording showing how I found it in less than a minute. 

http://recordit.co/lUa8bC5zzF

https://github.com/freeCodeCamp/guide/blob/792231f415bb421d2f15ce0a416835df59796cc2/src/pages/certifications/javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords/index.md
